### PR TITLE
Require enter on user input

### LINKED ISSUE #339: [NETE2ESDK]It should need to press enter to confirm when type y/n to continue with command uninstall
Build: dotnet-core-uninstall-1.7.615501
OS: Win 11 24h2 X64

Repro steps:
1. Run `dotnet-core-uninstall remove --sdk {version}` or  `dotnet-core-uninstall remove --runtime {version}`
2. Typing y or n with prompts 'Do you want to continue? 
3. Observe

Expected Result:
It needs to press enter to confirm before continuing.  Take the behavior in v1.7.550802 for example
Image

Actually Result:
Typing y or n without confirming will continue.
Image

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #339 by requiring the user to press enter to confirm when typing 'y' or 'n' to continue with the command uninstall.

### CODE REVIEW

File: src/dotnet-core-uninstall/Shared/Commands/UninstallCommandExec.cs [hunk 1]
```diff
@@ -216,13 +216,13 @@ public static bool AskWithWarningsForRequiredBundles(IDictionary<Bundle, string>
...
                 
-                var response = userResponse?.ToUpper() ?? Console.ReadKey().KeyChar.ToString().ToUpper();
+                var response = (userResponse ?? Console.ReadLine()).ToUpper();
 
                 if (response.Equals("N"))
                 {
                     return false;
                 }
-                if (!(response.Equals("Y") || response.Equals("YES")))
+                if (!response.Equals("Y"))
```
Comment (MiYanni) [inline src/dotnet-core-uninstall/Shared/Commands/UninstallCommandExec.cs:225]: So, `yes` doesn't work anymore? I guess it only asks for `y/n`, so that's fine by me.

**Review by MiYanni — APPROVED** [review]

File: src/dotnet-core-uninstall/Shared/Commands/UninstallCommandExec.cs (hunk 1 above)
Comment (edvilme) [reply src/dotnet-core-uninstall/Shared/Commands/UninstallCommandExec.cs:225]: Yes, this was briefly discussed with @joeloff https://github.com/dotnet/cli-lab/pull/331#discussion_r1974555062
