### PR TITLE
macOS: Show correct arm64 architecture

### LINKED ISSUE #297: [NETSDKE2E][MAC] The version of .NET core runtimes display x64 in dotnet-core-uninstall list when installing one arm64 runtime on M1
**To Reproduce**
1.Prepare a clean M1
2.install dotnet-core-uninstall(1.7.0) from [tar](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdnceng.visualstudio.com%2F_apis%2Fresources%2FContainers%2F17097018%2Fdrop%3FitemPath%3Ddrop%252Fdotnet-core-uninstall.tar.gz&data=05%7C02%7Cv-ainigao%40microsoft.com%7C069b3fabee524813ebcc08dc5cea5096%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638487408662461161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xUbJQZsisuqNG85%2BAF%2BNr42cMvu%2FPmYjGYBY%2FBfgLg4%3D&reserved=0)
3. Use the following commands to install the tool:

```
mkdir -p ~/dotnet-core-uninstall
tar -zxvf dotnet-core-uninstall.tar.gz -C ~/dotnet-core-uninstall
cd ~/dotnet-core-uninstall
./dotnet-core-uninstall list
```
4.Install 8.0.4 osx-arm64 runtime from https://dotnet.microsoft.com/en-us/download/dotnet/8.0
5. Run "./dotnet-core-uninstall list"
6.check the output of dotnet-core-uninstall list

**Expected Result:**
The version of .NET core runtimes should display arm64 in dotnet-core-uninstall list when installing one arm64 runtime on M1.

**Actual Result:**
The version of .NET core runtimes display x64 in dotnet-core-uninstall list when installing one arm64 runtime on M1
image
Dotnet --info after install the 8.0.4 osx-arm64 runtime
image

### PR DESCRIPTION
**Pull request by edvilme**
Closes #297 #221 
When listing runtimes and sdk's on arm Macs, the architecture should be displayed as arm64 instead of x64.

Currently this is not figured out on a by version lookup, but based on the first directory on the sdk installs directory

`list`
image

`dry-run`
image

### CODE REVIEW

**Review by Forgind — COMMENTED** [review]
How have you tested this? I don't see code changes that I have a problem with, but I don't know without testing whether this is sufficient or not, and I don't have an M1 mac for testing myself.

**Comment by edvilme** [comment]
Yes, tested this on an M1 Mac VM with several arm64 and one x64 sdks installed. I'm also ok with performing more tests (installing the x64 version first as it seems to have an effect on the current implementation) beforehand :)

File: src/dotnet-core-uninstall/MacOs/FileSystemExplorer.cs [hunk 1]
```diff
@@ -26,44 +26,40 @@ internal class FileSystemExplorer : IBundleCollector
...
                 runtimes = runtimes.Concat(GetInstalledBundles<RuntimeVersion>(
-                    BundleArch.X64,
-                    DotNetRuntimeInstallPath(DotNetInstallPath),
-                    DotNetAspAllInstallPath(DotNetInstallPath),
-                    DotNetAspAppInstallPath(DotNetInstallPath),
-                    DotNetHostFxrInstallPath(DotNetInstallPath)));
+                    DotNetRuntimeInstallPath(EmulatedDotNetInstallPath),
+                    DotNetAspAllInstallPath(EmulatedDotNetInstallPath),
+                    DotNetAspAppInstallPath(EmulatedDotNetInstallPath),
+                    DotNetHostFxrInstallPath(EmulatedDotNetInstallPath)));
```
Comment (edvilme) [inline src/dotnet-core-uninstall/MacOs/FileSystemExplorer.cs:43]: This was also addressed in #228

**Review by Forgind — APPROVED** [review]
